##---------------------------------------------------------------------##
## Experiment 0
# EEG data parameters
epoch_length: 2
n_electrodes: 9
s_freq:       256

# Subject parameters
subjects :    ['7704','7702','7703','7000','7705','0000','7706','6004','2006',
'7707','7708','7709','7710','7711','7712','7713','7714',
'7715','7716','7717','7718','7719']
expert :      ['7704','7702','7711','7714','7718','7719']
novice :      [7703','7000','7705','0000','7706','6004','2006',
'7707','7708','7709','7710','7712','7713','7715','7716','7717']
test_subjects : []
features :    ['detected', 'drone_number' , 'target_shape', 'time', 'task_stage',
'reaction_time', 'fixation_rate','situation_awareness','transition_ratio', 'glance_ratio', 'pupil_size',
'mental_workload', 'avg_mental_workload', 'high_engagement', 'low_engagement', 'distraction']
task_type :   ['no_force', 'error_reduction', 'error_augmentation']

# Path
raw_data_path : 'data/raw/'
processed_dataset : 'data/processed/processed_exp_0_dataset.h5'
processed_dataframe : 'data/processed/processed_exp_0_dataframe.pkl'
##---------------------------------------------------------------------##
